title: NestJS template project with DDD and DevOps
author:
  name: Andrea Acampora
  url: https://github.com/andrea-acampora
social:
  name: Andrea Acampora
  links:
    - https://www.linkedin.com/in/andrea-acampora-5b3842147
email: andrea.acampora@protonmail.com
description: > 
  Ready-to-use project following Domain-Driven Design, Clean Architecture and Functional Programming best practices,
  combined with some DevOps techniques such as Continuous Integration, Continuous Delivery and Quality Assurance.
repository: "https://github.com/andrea-acampora/nestjs-ddd-quickstarter"
github_username: andrea-acampora
baseurl: ""
keywords: nestjs, ddd, nodejs, devops, clean-architecture, domain-driven-design
lang: en
timezone: Europe/Paris
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


