name: Build

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'README.md'
      - 'renovate.json'
  pull_request:

jobs:
  Build:
    strategy:
      matrix:
        node-version: [ '18.x', '20.x', '22.x' ]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db-test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Check style
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Unit Tests
        run: npm run test
      - name: E2E Tests
        run: npm run test:e2e
        env:
          DATABASE_NAME: db-test
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 15432
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres